#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 18 20:19:13 2020

@author: Emily
"""

import CreaturesAndThings
import GUI
import time
import foxAndRabbit as population

things = []

for i in range(10):
    things.append(population.Rabbit())
    
for i in range(2):
    things.append(population.Fox())

GUI.begin(500, 400)
GUI.updateAll(things)
    
for i in range(1000):
    for thing in things:
        thing.tick(0,0)
#    GUI.updateAll
    time.sleep(.1)
    
GUI.waitForClick()
GUI.close()